name: reflecto
description: >
  A Navand app.
publish_to: none
environment:
  sdk: ^3.2.3
dependencies:
  navand: ^1.0.1
  shamsi_date: ^1.0.2
dev_dependencies:
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
  lints: ^3.0.0
